In [1]:
'''
auto sales scraper
~~~~
- read site html
- extracts tables from page
- finds month/year for table
- changes column names for table
- scrape the tables for the site
- scrape all the tables for all the urls
- merge table data into one dataframe
- run everything and backup as csv
'''

'\nauto sales scraper\n~~~~\n- read site html\n- extracts tables from page\n- finds month/year for table\n- changes column names for table\n- scrape the tables for the site\n- scrape all the tables for all the urls\n- merge table data into one dataframe\n- run everything and backup as csv\n'

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import csv

In [3]:
list_of_urls = ["http://www.goodcarbadcar.net/2019/05/april-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2019/04/march-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2019/03/february-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2019/02/january-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2019/01/december-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2018/12/november-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2018/11/october-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2018/10/september-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2018/09/august-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2018/08/july-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2018/07/june-2018-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 'http://www.goodcarbadcar.net/2018/06/may-2018-ytd-u-s-vehicle-sales-rankings-the-best-selling-vehicles-in-america/',
 'http://www.goodcarbadcar.net/2018/05/april-2018-ytd-u-s-vehicle-sales-rankings-top-284-best-selling-vehicles-in-america-every-vehicle-ranked/',
 "http://www.goodcarbadcar.net/2018/04/march-2018-ytd-u-s-vehicle-sales-rankings-top-284-best-selling-vehicles-in-america-every-vehicle-ranked/'",
 "http://www.goodcarbadcar.net/2018/03/february-2018-top-287-best-selling-vehicles-america-every-vehicle-ranked/'",
 "http://www.goodcarbadcar.net/2018/02/january-2018-top-284-best-selling-vehicles-in-america-every-vehicle-ranked/'",
 "http://www.goodcarbadcar.net/2017/02/january-2017-usa-vehicle-sales-rankings-by-mode/',",
 "http://www.goodcarbadcar.net/2017/01/usa-2016-vehicle-sales-by-model-manufacturer-brand/',",
 "http://www.goodcarbadcar.net/2016/12/november-2016-ytd-usa-vehicle-sales-rankings-by-mode/'",
 "http://www.goodcarbadcar.net/2016/11/october-2016-usa-vehicle-sales-by-model-rankings/',",
 "http://www.goodcarbadcar.net/2016/10/usa-september-2016-new-vehicle-sales-by-model-brand-manufacturer/',",
 "http://www.goodcarbadcar.net/2016/09/usa-august-2016-auto-sales-by-model-brand/'",
 "http://www.goodcarbadcar.net/2016/08/usa-all-vehicle-sales-by-model-july-2016-ytd/'",
 "http://www.goodcarbadcar.net/2016/07/usa-vehicle-sales-by-model-june-2016-first-half/',",
 'http://www.goodcarbadcar.net/2016/06/may-2016-ytd-usa-vehicle-sales-by-mode/',
 'http://www.goodcarbadcar.net/2016/05/usa-vehicle-sales-by-model-april-2016-ytd-all-autos/',
 "http://www.goodcarbadcar.net/2016/04/usa-march-2016-q1-new-vehicle-sales-by-mode/',",
 "http://www.goodcarbadcar.net/2016/03/usa-auto-sales-by-model-every-vehicle-february-2016-ytd/'",
 "http://www.goodcarbadcar.net/2016/02/usa-january-2016-vehicle-sales-rankings-by-mode/',",
 "http://www.goodcarbadcar.net/2016/01/usa-vehicle-sales-by-model-2015-calendar-year-december/',",
 "http://www.goodcarbadcar.net/2016/04/usa-march-2016-q1-new-vehicle-sales-by-mode/',",
 "http://www.goodcarbadcar.net/2015/03/usa-february-2015-new-vehicle-sales-figures-by-model-make/',",
 "http://www.goodcarbadcar.net/2015/02/complete-january-2015-auto-sales-figures-every-model-and-brand/'",
 "http://www.goodcarbadcar.net/2015/01/2014-usa-new-vehicle-sales-figures-by-mode/',",
 "http://www.goodcarbadcar.net/2014/12/usa-november-2014-vehicle-sales-figures-by-mode/',",
 "http://www.goodcarbadcar.net/2014/11/usa-vehicle-sales-rankings-by-model-october-2014-ytd/'",
 "http://www.goodcarbadcar.net/2014/10/usa-auto-sales-figures-by-model-september-2014-ytd-sales-figures/'",
 "http://www.goodcarbadcar.net/2014/09/usa-auto-sales-figures-by-model-august-2014-ytd-sales-figures/'",
 "http://www.goodcarbadcar.net/2014/08/usa-auto-sales-rankings-by-make-model-july-2014-ytd-sales-figures/'",
 "http://www.goodcarbadcar.net/2014/07/usa-all-vehicle-nameplates-ranked-june-2014-ytd-sales-figures/'",
 "http://www.goodcarbadcar.net/2014/06/usa-all-vehicle-nameplates-ranked-may-2014-ytd-sales-figures/'",
 "http://www.goodcarbadcar.net/2014/05/usa-all-vehicle-nameplates-ranked-april-2014-ytd-sales-figures/'",
 "http://www.goodcarbadcar.net/2014/04/march-2014-usa-auto-sales-make-and-model-all-vehicles-ranked/'",
 "http://www.goodcarbadcar.net/2014/03/february-2014-usa-auto-sales-make-and-model-all-vehicles-ranked/'",
 "http://www.goodcarbadcar.net/2014/02/january-2014-usa-vehicle-sales-rankings-by-mode/',",
 "http://www.goodcarbadcar.net/2014/01/usa-vehicle-sales-rankings-by-model-december-2013-year-end/',",
 "http://www.goodcarbadcar.net/2013/12/usa-auto-sales-rankings-by-model-november-2013-ytd/'",
 'http://www.goodcarbadcar.net/2013/11/usa-auto-sales-brand-rankings-october-2013-ytd-sales-figures/',
 "http://www.goodcarbadcar.net/2013/10/usa-auto-sales-rankings-by-model-september-2013-ytd/'",
 'http://www.goodcarbadcar.net/2013/09/usa-auto-sales-rankings-by-model-august-2013-ytd/',
 'http://www.goodcarbadcar.net/2013/08/usa-vehicle-sales-rankings-by-model-july-2013-ytd/',
 'http://www.goodcarbadcar.net/2013/07/usa-auto-sales-rankings-by-model-june-2013-ytd/',
 'http://www.goodcarbadcar.net/2013/06/usa-vehicle-sales-rankings-by-model-may-2013-ytd/',
 "http://www.goodcarbadcar.net/2013/05/usa-vehicle-sales-rankings-by-model-april-2013-ytd/'",
 "http://www.goodcarbadcar.net/2013/04/march-2013-usa-vehicle-sales-rankings-by-mode/',",
 "http://www.goodcarbadcar.net/2013/03/february-2013-usa-vehicle-sales-rankings-by-mode/',",
 'http://www.goodcarbadcar.net/2013/02/january-2013-usa-auto-sales-rankings-by-mode/',
 'http://www.goodcarbadcar.net/2012/12/november-2012-usa-ytd-auto-sales-rankings-by-mode/',
 'http://www.goodcarbadcar.net/2012/11/october-2012-usa-ytd-auto-sales-rankings-by-mode/',
 'http://www.goodcarbadcar.net/2012/10/september-2012-usa-ytd-auto-sales-rankings/',
 'http://www.goodcarbadcar.net/2012/09/august-2012-ytd-all-vehicle-rankings/',
 'http://www.goodcarbadcar.net/2012/08/usa-july-2012-ytd-auto-sales-rankings/',
 'http://www.goodcarbadcar.net/2012/07/us-june-2012-sales-figures-rankings-ytd/',
 'http://www.goodcarbadcar.net/2012/06/us-car-sales-rankings-june-2012/',
 "http://www.goodcarbadcar.net/2012/05/april-2012-us-car-sales-rankings-a/',",
 "http://www.goodcarbadcar.net/2012/04/us-best-selling-autos-march-2012-ytd/'",
 'http://www.goodcarbadcar.net/2012/03/us-best-selling-autos-february-2012-ytd/',
 'http://www.goodcarbadcar.net/2012/03/us-best-selling-autos-january-2012/',
 "http://www.goodcarbadcar.net/2012/01/us-best-selling-vehicles-december-2011/',",
 "http://www.goodcarbadcar.net/2011/12/us-best-selling-vehicles-november-2011/'",
 'http://www.goodcarbadcar.net/2011/11/us-best-selling-vehicles-october-2011/']

In [4]:
bad_url = 'http://www.goodcarbadcar.net/2013/01/2012-usa-auto-sales-rankings-by-model7/'

In [5]:
def read_site_html(url):
    '''
    pulls text of tables from inputted url
    returns as list of dataframes
    '''
    html = requests.get(url).text
    dataframes = pd.read_html(html, header=0)
    return dataframes

In [18]:
list_of_urls[0]
list_of_urls[1]

"http://www.goodcarbadcar.net/2019/04/march-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',"

In [19]:
df1 = read_site_html(list_of_urls[0])
df2 = read_site_html(list_of_urls[1])

In [21]:
pull_useful_tables(df2)

,Model,Month,Month LY,Change,YTD,YTD LY,YTD Change,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Fiat 124 Spider,214,325,-34.15,513,731,-29.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW 2-Series,746,1179,-36.73,2062,2768,-25.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chrysler 200,8,189,-95.77,26,659,-96.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mazda 3,6009,7760,-22.56,15215,19655,-22.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW 3-Series,4620,4845,-4.64,8225,13651,-39.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Chrysler 300,3704,6223,-40.48,8290,12992,-36.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Nissan 370Z,263,447,-41.16,647,983,-34.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BMW 4-Series,1875,3230,-41.95,7402,6939,6.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alfa Romeo 4C,18,22,-18.18,41,54,-24.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Toyota 4Runner,12510,11761,6.37,32829,31550,4.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,BMW 5-Series,3690,4397,-16.08,10345,10038,3.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Fiat 500,310,439,-29.38,778,1309,-40.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Fiat 500L,61,173,-64.74,168,395,-57.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Fiat 500X,262,607,-56.84,755,1579,-52.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mazda 6,3396,3734,-9.05,6921,7532,-8.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,BMW 6-Series,149,471,-68.37,625,1030,-39.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Volvo 60-Series,1501,1156,29.84,3959,3153,25.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,BMW 7-Series,988,823,20.05,2293,1800,27.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Porsche 718,239,489,-51.12,665,1352,-50.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BMW 8-Series,364,0,0.00,601,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Toyota 86 / FR-S,320,491,-34.83,807,1169,-30.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Volvo 90-Series,346,1131,-69.41,1227,2659,-53.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Porsche 911,803,883,-9.06,2894,2511,15.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Mercedes-Benz A-Class,890,0,0.00,890,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Audi A3,1182,1823,-35.16,2669,4476,-40.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Audi A4,2652,3296,-19.54,5779,7651,-24.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Audi A5,2224,2587,-14.03,5478,6074,-9.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Audi A6,1963,1171,67.63,5358,2764,93.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Audi A7,672,367,83.11,1766,843,109.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Audi A8,261,135,93.33,787,371,112.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Chevrolet Trax,8732,8207,6.40,24580,20482,20.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Audi TT,122,186,-34.41,210,367,-42.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Toyota Tundra,10351,10697,-3.23,25100,26318,-4.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Hyundai Tuscon,11976,11806,1.44,28831,27882,3.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Lexus UX,1776,0,0.00,3925,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Hyundai Veloster,2055,1445,42.21,3891,3040,27.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,Toyota Venza,1,0,0.00,1,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,Nissan Versa,10933,10921,0.11,24992,25365,-1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,Chevrolet Volt,895,1782,-49.78,2520,3478,-27.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,Jeep Wrangler,21963,27829,-21.08,49988,55504,-9.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,BMW X1,3470,3717,-6.65,5856,8251,-29.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,BMW X2,1079,947,13.94,2951,947,211.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,BMW X3,6727,4547,47.94,14568,10782,35.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,BMW X4,577,513,12.48,1436,1417,1.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,BMW X5,4460,4840,-7.85,11912,12076,-1.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,BMW X6,646,763,-15.33,2100,2019,4.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,BMW X7,2186,0,0.00,2186,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,Volvo XC40,1550,1001,54.85,3577,1072,233.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,Volvo XC60,2936,2379,23.41,6636,6033,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,Volvo XC90,3236,2796,15.74,6659,7389,-9.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,Jaguar XE,658,609,8.05,1841,1635,12.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,Jaguar XF,212,215,-1.40,586,580,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,Jaguar XJ,128,191,-32.98,409,613,-33.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,Cadillac XT4,2496,0,0.00,7026,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,Cadillac XT5,4717,6188,-23.77,13278,14845,-10.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,Cadillac XTS,1327,1735,-23.52,3734,4898,-23.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,Toyota Yaris,3999,3062,30.60,7894,7960,-0.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,GMC Yukon,5310,3257,63.03,14947,8894,68.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,BMW Z4,201,0,0.00,201,2,9950.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Model,Month,Month LY,NaN,YTD,YTD LY,NaN,NaN,"∑ = 1,552,126","∑ = 1,653,052",NaN,"∑ = 3,982,359","∑ = 4,107,751",NaN,NaN,"∑ = 3,982,368","∑ = 4,120,229",NaN,NaN,NaN

In [24]:
df_list = [df1, df2]

In [25]:
def pull_useful_tables(dataframes):
    '''
    deletes tables with no data from list of dataframes
    returns single dataframe for month
    '''
    list_of_dfs = []
    if len(dataframes) == 1:
        return dataframes[0]
    else:
        for df in dataframes:
            if df.columns[0] == 'Rank':
                list_of_dfs.append(df)
        try:
            merged_table = pd.concat(list_of_dfs)
            return merged_table
        except:
            return list_of_dfs

In [29]:
df1 = pull_useful_tables(df1)

In [30]:
df1

,Model,Month,Month LY,Change,YTD,YTD LY,YTD Change,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Fiat 124 Spider,329,337,-2.37,842,1068,-21.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW 2-Series,581,879,-33.90,2643,3647,-27.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chrysler 200,3,95,-96.84,29,754,-96.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mazda 3,4351,4725,-7.92,19566,24380,-19.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW 3-Series,3642,3550,2.59,11867,17201,-31.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Chrysler 300,1998,3913,-48.94,10288,16905,-39.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Nissan 370Z,177,260,-31.92,824,1243,-33.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BMW 4-Series,1214,2473,-50.91,8616,9412,-8.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alfa Romeo 4C,27,22,22.73,68,76,-10.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Toyota 4Runner,10055,9970,0.85,42884,41520,3.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,BMW 5-Series,2857,3056,-6.51,13202,13094,0.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Fiat 500,273,335,-18.51,1051,1644,-36.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Fiat 500L,72,168,-57.14,240,563,-57.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Fiat 500X,257,564,-54.43,1012,2143,-52.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mazda 6,2340,2909,-19.56,9261,10441,-11.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,BMW 6-Series,96,398,-75.88,721,1428,-49.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Volvo 60-Series,1259,1392,-9.55,5218,4545,14.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,BMW 7-Series,567,546,3.85,2860,2346,21.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Porsche 718,612,604,1.32,1277,1956,-34.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BMW 8-Series,275,0,0.00,876,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Toyota 86 / FR-S,268,337,-20.47,1075,1506,-28.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Volvo 90-Series,333,763,-56.36,1560,3422,-54.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Porsche 911,655,940,-30.32,3549,3451,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Mercedes-Benz A-Class,804,0,0.00,1694,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Audi A3,681,1593,-57.25,3350,6069,-44.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Audi A4,1860,3126,-40.50,7639,10777,-29.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Audi A5,1685,2169,-22.31,7163,8243,-13.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Audi A6,1374,1172,17.24,6732,3936,71.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Audi A7,441,280,57.50,2207,1123,96.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Audi A8,187,83,125.30,974,454,114.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,Volkswagen Tiguan,10564,8684,21.65,37261,36112,3.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,Nissan Titan,2489,2670,-6.78,12172,15394,-20.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,Acura TLX,2096,2914,-28.07,9125,11877,-23.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Volkswagen Touareg,12,170,-92.94,98,1108,-91.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,Chrysler Town and Country,2,0,0.00,3,3,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,Audi TT,114,167,-31.74,324,534,-39.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,Toyota Tundra,8862,9457,-6.29,33962,35775,-5.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,Hyundai Tuscon,8682,12903,-32.71,37513,40785,-8.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,Lexus UX,1273,0,0.00,5198,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,Hyundai Veloster,1554,924,68.18,5445,3964,37.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,Toyota Venza,1,0,0.00,2,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,Nissan Versa,6710,5998,11.87,31702,31363,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,Dodge Viper,1,2,-50.00,2,11,-81.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,Jeep Wrangler,22422,29776,-24.70,72410,85280,-15.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,BMW X1,1618,2501,-35.31,7474,10752,-30.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,BMW X2,822,1069,-23.11,3773,2016,87.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,BMW X3,4321,3865,11.80,18889,14647,28.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,BMW X4,638,193,230.57,2074,1610,28.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,BMW X5,3781,3800,-0.50,15693,15876,-1.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,BMW X6,424,592,-28.38,2524,2611,-3.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,BMW X7,2291,0,0.00,4477,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,Volvo XC40,1824,1404,29.91,5401,2476,118.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,Volvo XC60,2251,2492,-9.67,8887,8525,4.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,Volvo XC90,2700,2282,18.32,9359,9671,-3.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,Jaguar XE,217,299,-27.42,2058,1934,6.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,Jaguar XF,71,142,-50.00,657,722,-9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,Jaguar XJ,93,100,-7.00,502,713,-29.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,Toyota Yaris,3885,3194,21.63,11779,11154,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,BMW Z4,271,0,0.00,472,2,23500.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,Model,Month,Month LY,NaN,YTD,YTD LY,NaN,NaN,"∑ = 903,710","∑ = 908,700",NaN,"∑ = 3,638,126","∑ = 3,709,904",NaN,NaN,"∑ = 3,982,368","∑ = 4,120,229",NaN,NaN,NaN

In [31]:
months = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 
          'august', 'september', 'october', 'november', 'december']
years = list(range(2010,2020))

In [32]:
def find_year_and_month(url):
    '''
    parses url string to find month and year & last year of table
    returns tuple of month as string and year & last year as integers
    '''
    month = [month for month in months if month in url]
    year = min([year for year in years if str(year) in url])
    last_year = year - 1
    try:
        month = month[0]
    except:
        month = 'NULL'
    return month, year, last_year

In [33]:
df3 = change_column_to_month(df1, list_of_urls[0])

In [34]:
df3

                         Model 2019_april 2018_april
0              Fiat 124 Spider        329        337
1                 BMW 2-Series        581        879
2                 Chrysler 200          3         95
3                      Mazda 3       4351       4725
4                 BMW 3-Series       3642       3550
5                 Chrysler 300       1998       3913
6                  Nissan 370Z        177        260
7                 BMW 4-Series       1214       2473
8                Alfa Romeo 4C         27         22
9               Toyota 4Runner      10055       9970
10                BMW 5-Series       2857       3056
11                    Fiat 500        273        335
12                   Fiat 500L         72        168
13                   Fiat 500X        257        564
14                     Mazda 6       2340       2909
15                BMW 6-Series         96        398
16             Volvo 60-Series       1259       1392
17                BMW 7-Series        567        546
18                 Porsche 718        612        604
19                BMW 8-Series        275          0
20            Toyota 86 / FR-S        268        337
21             Volvo 90-Series        333        763
22                 Porsche 911        655        940
23       Mercedes-Benz A-Class        804          0
24                     Audi A3        681       1593
25                     Audi A4       1860       3126
26                     Audi A5       1685       2169
27                     Audi A6       1374       1172
28                     Audi A7        441        280
29                     Audi A8        187         83
..                         ...        ...        ...
197          Volkswagen Tiguan      10564       8684
198               Nissan Titan       2489       2670
199                  Acura TLX       2096       2914
200         Volkswagen Touareg         12        170
201  Chrysler Town and Country          2          0
202                    Audi TT        114        167
203              Toyota Tundra       8862       9457
204             Hyundai Tuscon       8682      12903
205                   Lexus UX       1273          0
206           Hyundai Veloster       1554        924
207               Toyota Venza          1          0
208               Nissan Versa       6710       5998
209                Dodge Viper          1          2
210              Jeep Wrangler      22422      29776
211                     BMW X1       1618       2501
212                     BMW X2        822       1069
213                     BMW X3       4321       3865
214                     BMW X4        638        193
215                     BMW X5       3781       3800
216                     BMW X6        424        592
217                     BMW X7       2291          0
218                 Volvo XC40       1824       1404
219                 Volvo XC60       2251       2492
220                 Volvo XC90       2700       2282
221                  Jaguar XE        217        299
222                  Jaguar XF         71        142
223                  Jaguar XJ         93        100
224               Toyota Yaris       3885       3194
225                     BMW Z4        271          0
226                      Model      Month   Month LY

[227 rows x 3 columns]

In [9]:
def change_column_to_month(dataframe, url):
    '''
    changes name of columns in dataframe to proper months, years
    cuts unneeded columns of dataframe
    '''
    alternate_columns = ['Month', 'US']
    dataframe.rename(columns={'Vehicle': 'Model'}, inplace=True)
    dataframe.rename(columns={'Best-Selling Vehicle': 'Model'}, inplace=True)
    if dataframe.columns[1] in alternate_columns:
        table_date = find_year_and_month(url)
        year_month = str(table_date[1]) + '_' + table_date[0]
        prior_year_month = str(table_date[2]) + '_' + table_date[0]   
        dataframe.rename(columns={'Month':year_month, 'Month LY':prior_year_month}, inplace=True)
        dataframe.rename(columns={'US':year_month, 'US LY':prior_year_month}, inplace=True)
        return dataframe.iloc[:,0:3]
    else:
        return dataframe.iloc[:,1:4]

In [37]:
x

                         Model 2019_april 2018_april
0              Fiat 124 Spider        329        337
1                 BMW 2-Series        581        879
2                 Chrysler 200          3         95
3                      Mazda 3       4351       4725
4                 BMW 3-Series       3642       3550
5                 Chrysler 300       1998       3913
6                  Nissan 370Z        177        260
7                 BMW 4-Series       1214       2473
8                Alfa Romeo 4C         27         22
9               Toyota 4Runner      10055       9970
10                BMW 5-Series       2857       3056
11                    Fiat 500        273        335
12                   Fiat 500L         72        168
13                   Fiat 500X        257        564
14                     Mazda 6       2340       2909
15                BMW 6-Series         96        398
16             Volvo 60-Series       1259       1392
17                BMW 7-Series        567        546
18                 Porsche 718        612        604
19                BMW 8-Series        275          0
20            Toyota 86 / FR-S        268        337
21             Volvo 90-Series        333        763
22                 Porsche 911        655        940
23       Mercedes-Benz A-Class        804          0
24                     Audi A3        681       1593
25                     Audi A4       1860       3126
26                     Audi A5       1685       2169
27                     Audi A6       1374       1172
28                     Audi A7        441        280
29                     Audi A8        187         83
..                         ...        ...        ...
197          Volkswagen Tiguan      10564       8684
198               Nissan Titan       2489       2670
199                  Acura TLX       2096       2914
200         Volkswagen Touareg         12        170
201  Chrysler Town and Country          2          0
202                    Audi TT        114        167
203              Toyota Tundra       8862       9457
204             Hyundai Tuscon       8682      12903
205                   Lexus UX       1273          0
206           Hyundai Veloster       1554        924
207               Toyota Venza          1          0
208               Nissan Versa       6710       5998
209                Dodge Viper          1          2
210              Jeep Wrangler      22422      29776
211                     BMW X1       1618       2501
212                     BMW X2        822       1069
213                     BMW X3       4321       3865
214                     BMW X4        638        193
215                     BMW X5       3781       3800
216                     BMW X6        424        592
217                     BMW X7       2291          0
218                 Volvo XC40       1824       1404
219                 Volvo XC60       2251       2492
220                 Volvo XC90       2700       2282
221                  Jaguar XE        217        299
222                  Jaguar XF         71        142
223                  Jaguar XJ         93        100
224               Toyota Yaris       3885       3194
225                     BMW Z4        271          0
226                      Model      Month   Month LY

[227 rows x 3 columns]

In [10]:
def scrape_one_page(url):
    '''
    takes in the site url, scrapes tables, changes column names
    returns dataframes using helper functions
    '''
    tables = read_site_html(url)
    df = pull_useful_tables(tables)
    df = change_column_to_month(df, url)
    return df

In [38]:
x = scrape_one_page(list_of_urls[0])

In [39]:
y = scraper(list_of_urls[0:10])

In [41]:
y[2]

                    Model 2019_february 2018_february
0         Fiat 124 Spider           139           223
1            BMW 2-Series           738           949
2            Chrysler 200             6           219
3                 Mazda 3          4610          6070
4            BMW 3-Series          2379          4255
5            Chrysler 300          2508          4449
6             Nissan 370Z           211           312
7            BMW 4-Series          2685          2124
8           Alfa Romeo 4C            16            20
9          Toyota 4Runner          9984         10120
10           BMW 5-Series          2976          3185
11               Fiat 500           207           416
12              Fiat 500L            51           118
13              Fiat 500X           219           484
14                Mazda 6          1906          2246
15           BMW 6-Series           315           336
16        Volvo 60-Series          1058          1004
17           BMW 7-Series           851           615
18            Porsche 718           163           448
19           BMW 8-Series           138             0
20       Toyota 86 / FR-S           231           361
21        Volvo 90-Series           367           809
22            Porsche 911           990           775
23                Audi A3           823          1510
24                Audi A4          1436          2331
25                Audi A5          1603          1888
26                Audi A6          1506           842
27                Audi A7           474           268
28                Audi A8           242           124
29             GMC Acadia          9853         10705
..                    ...           ...           ...
249          Ford Transit         10055          9666
250  Ford Transit Connect          2823          2101
251    Chevrolet Traverse         10807         11548
252        Chevrolet Trax          7762          6169
253               Audi TT            77            76
254         Toyota Tundra          7590          7977
255        Hyundai Tuscon          9411          8438
256              Lexus UX          1358             0
257      Hyundai Veloster           981           851
258          Nissan Versa          7410          7196
259        Chevrolet Volt           796           983
260         Jeep Wrangler         15001         15936
261                BMW X1          1445          2857
262                BMW X2          1256             0
263                BMW X3          4706          3281
264                BMW X4           453           517
265                BMW X5          4360          4006
266                BMW X6           859           721
267            Volvo XC40           985            71
268            Volvo XC60          2229          1955
269            Volvo XC90          1996          2444
270             Jaguar XE           777           434
271             Jaguar XF           278           162
272             Jaguar XJ           109           191
273          Cadillac XT4          2219             0
274          Cadillac XT5          4193          4668
275          Cadillac XTS          1179          1943
276          Toyota Yaris          2572          2592
277             GMC Yukon          4720          2936
278                 Model         Month      Month LY

[279 rows x 3 columns]

In [11]:
def scraper(list_of_websites):
    '''
    takes in a list of urls, scrapes table on each page, regularizes column names,
    and adds the dataframe to a list of dataframes which is returned
    '''
    list_of_dataframes = []
    for url in list_of_urls:
        df = scrape_one_page(url)
        list_of_dataframes.append(df)
    return list_of_dataframes

In [44]:
z = merge_dataframes(y)

In [45]:
z

,Model,2019_april,2018_april_x,2019_march,2018_march_x,2019_february,2018_february_x,2019_january,2018_january_x,2018_december,...,February 2012 YTD,February 2011 YTD,January 2012_y,January 2011,December 2011,% Change_y,November 2011,% Change,October 2011,October 2010
0,Fiat 124 Spider,329,337,214,325,139,223,160,183,184,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW 2-Series,581,879,746,1179,738,949,578,640,718,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chrysler 200,3,95,8,189,6,219,12,251,6,...,16724,4482,7007,788,NaN,NaN,NaN,NaN,11205.0,2221.0
3,Mazda 3,4351,4725,6009,7760,4610,6070,4596,5825,5277,...,20475,13092,9200,5015,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW 3-Series,3642,3550,4620,4845,2379,4255,1226,4551,3184,...,14801,10635,6698,5763,NaN,NaN,NaN,NaN,NaN,NaN
5,Chrysler 300,1998,3913,3704,6223,2508,4449,2078,2320,3483,...,12630,2652,4960,1329,NaN,NaN,NaN,NaN,NaN,NaN
6,Nissan 370Z,177,260,263,447,211,312,173,224,202,...,970,1138,417,567,NaN,NaN,NaN,NaN,NaN,NaN
7,BMW 4-Series,1214,2473,1875,3230,2685,2124,2842,1585,1916,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alfa Romeo 4C,27,22,18,22,16,20,7,12,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Toyota 4Runner,10055,9970,12510,11761,9984,10120,10335,9669,13309,...,5987,7589,2919,3829,NaN,NaN,NaN,NaN,NaN,NaN
10,BMW 5-Series,2857,3056,3690,4397,2976,3185,3679,2456,4756,...,7258,8562,3216,4350,NaN,NaN,NaN,NaN,NaN,NaN
11,Fiat 500,273,335,310,439,207,416,261,454,418,...,5138,—–,1911,—–,NaN,NaN,NaN,NaN,NaN,NaN
12,Fiat 500L,72,168,61,173,51,118,56,104,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Fiat 500X,257,564,262,607,219,484,274,488,336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mazda 6,2340,2909,3396,3734,1906,2246,1619,1552,2357,...,10030,5096,4929,2258,NaN,NaN,NaN,NaN,NaN,NaN
15,BMW 6-Series,96,398,149,471,315,336,161,223,330,...,938,189,409,83,NaN,NaN,NaN,NaN,NaN,NaN
16,Volvo 60-Series,1259,1392,1501,1156,1058,1004,1400,993,302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,BMW 7-Series,567,546,988,823,851,615,454,362,983,...,2100,1735,977,626,NaN,NaN,NaN,NaN,NaN,NaN
18,Porsche 718,612,604,239,489,163,448,263,415,237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BMW 8-Series,275,0,364,0,138,0,99,0,223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Toyota 86 / FR-S,268,337,320,491,231,361,256,317,295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Volvo 90-Series,333,763,346,1131,367,809,514,719,664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Porsche 911,655,940,803,883,990,775,1101,853,789,...,1539,841,681,436,NaN,NaN,NaN,NaN,NaN,NaN
23,Mercedes-Benz A-Class,804,0,890,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Audi A3,681,1593,1182,1823,823,1510,664,1143,792,...,1054,1101,585,715,NaN,NaN,NaN,NaN,NaN,NaN
25,Audi A4,1860,3126,2652,3296,1436,2331,1691,2024,1881,...,5395,5253,2676,2483,NaN,NaN,NaN,NaN,NaN,NaN
26,Audi A4,1860,3126,2652,3296,1436,2331,1691,2024,1881,...,5395,5253,2676,2483,NaN,NaN,NaN,NaN,NaN,NaN
27,Audi A5,1685,2169,2224,2587,1603,1888,1651,1599,1746,...,1997,2196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Audi A6,1374,1172,1963,1171,1506,842,1889,751,3058,...,2102,1188,1130,594,NaN,NaN,NaN,NaN,NaN,NaN
29,Audi A7,441,280,672,367,474,268,620,208,1095,...,1227,—–,643,—–,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3849,——————————–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3850,—–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3851,Chevrolet Silverado/GMC Sierra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3852,Hyundai Sonata/Kia Optima,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3853,Honda Accord/Crosstour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3854,Chevrolet Equinox/GMC Terrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3855,Dodge Grand Caravan / Chrysler Town & Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3856,Chrysler 200/Dodge Avenger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3857,Subaru Outback/Legacy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3858,Hyundai Accent/Kia Rio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3859,Chevrolet Tahoe/GMC Yukon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3860,Hyundai Tucson/Kia Sportage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3861,Chevrolet Suburban / GMC Yukon XL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3862,Nissan Frontier/Suzuki Equator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3863,Chevrolet Colorado/GMC Canyon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3864,Audi A4/A5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3865,Audi A6/A7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3866,Mercedes-Benz S-Class/CL-Class,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3867,Scion FR-S/Subaru BRZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3868,Porsche Boxster/Cayman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3869,Nissan LEAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1154,154,676,87,NaN,NaN,NaN,NaN,NaN,NaN
3870,Lexus ES350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5407,4813,2410,2215,NaN,NaN,NaN,NaN,NaN,NaN
3871,Infiniti EX35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,632,989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3872,Chevrolet Caprive PPV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3873,Porsche Boxsster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3874,* Prius Liftback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24969,24174,8500,10635,NaN,NaN,NaN,NaN,NaN,NaN
3875,* Prius V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7138,—–,3055,—–,NaN,NaN,NaN,NaN,NaN,NaN
3876,* Prius Plug-In,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21,—–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3877,* Prius C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,—–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3878,Toyota Prius/Prius V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11555,10635,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
def merge_dataframes(list_of_df):
    '''
    merges all dataframes on the model column, returns a single dataframe
    '''
    merged_df  = pd.DataFrame(columns=['Model'])
    for df in list_of_df:
        merged_df = merged_df.merge(df, how='outer', on='Model')
        merged_df.drop_duplicates(inplace=True)
    return merged_df

In [47]:
def run(lst_of_urls):
    '''
    runs scraper and merges all dataframes.
    saves dataframe as a csv and returns a dataframe
    '''
    df_list = scraper(lst_of_urls)
    df = merge_dataframes(df_list)
    df.to_csv('merged_dataframe.csv')
    return df

In [48]:
df = run(list_of_urls)

In [49]:
df

,Model,2019_april,2018_april_x,2019_march,2018_march_x,2019_february,2018_february_x,2019_january,2018_january_x,2018_december,...,February 2012 YTD,February 2011 YTD,January 2012_y,January 2011,December 2011,% Change_y,November 2011,% Change,October 2011,October 2010
0,Fiat 124 Spider,329,337,214,325,139,223,160,183,184,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW 2-Series,581,879,746,1179,738,949,578,640,718,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chrysler 200,3,95,8,189,6,219,12,251,6,...,16724,4482,7007,788,NaN,NaN,NaN,NaN,11205.0,2221.0
3,Mazda 3,4351,4725,6009,7760,4610,6070,4596,5825,5277,...,20475,13092,9200,5015,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW 3-Series,3642,3550,4620,4845,2379,4255,1226,4551,3184,...,14801,10635,6698,5763,NaN,NaN,NaN,NaN,NaN,NaN
5,Chrysler 300,1998,3913,3704,6223,2508,4449,2078,2320,3483,...,12630,2652,4960,1329,NaN,NaN,NaN,NaN,NaN,NaN
6,Nissan 370Z,177,260,263,447,211,312,173,224,202,...,970,1138,417,567,NaN,NaN,NaN,NaN,NaN,NaN
7,BMW 4-Series,1214,2473,1875,3230,2685,2124,2842,1585,1916,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alfa Romeo 4C,27,22,18,22,16,20,7,12,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Toyota 4Runner,10055,9970,12510,11761,9984,10120,10335,9669,13309,...,5987,7589,2919,3829,NaN,NaN,NaN,NaN,NaN,NaN
10,BMW 5-Series,2857,3056,3690,4397,2976,3185,3679,2456,4756,...,7258,8562,3216,4350,NaN,NaN,NaN,NaN,NaN,NaN
11,Fiat 500,273,335,310,439,207,416,261,454,418,...,5138,—–,1911,—–,NaN,NaN,NaN,NaN,NaN,NaN
12,Fiat 500L,72,168,61,173,51,118,56,104,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Fiat 500X,257,564,262,607,219,484,274,488,336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mazda 6,2340,2909,3396,3734,1906,2246,1619,1552,2357,...,10030,5096,4929,2258,NaN,NaN,NaN,NaN,NaN,NaN
15,BMW 6-Series,96,398,149,471,315,336,161,223,330,...,938,189,409,83,NaN,NaN,NaN,NaN,NaN,NaN
16,Volvo 60-Series,1259,1392,1501,1156,1058,1004,1400,993,302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,BMW 7-Series,567,546,988,823,851,615,454,362,983,...,2100,1735,977,626,NaN,NaN,NaN,NaN,NaN,NaN
18,Porsche 718,612,604,239,489,163,448,263,415,237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BMW 8-Series,275,0,364,0,138,0,99,0,223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Toyota 86 / FR-S,268,337,320,491,231,361,256,317,295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Volvo 90-Series,333,763,346,1131,367,809,514,719,664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Porsche 911,655,940,803,883,990,775,1101,853,789,...,1539,841,681,436,NaN,NaN,NaN,NaN,NaN,NaN
23,Mercedes-Benz A-Class,804,0,890,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Audi A3,681,1593,1182,1823,823,1510,664,1143,792,...,1054,1101,585,715,NaN,NaN,NaN,NaN,NaN,NaN
25,Audi A4,1860,3126,2652,3296,1436,2331,1691,2024,1881,...,5395,5253,2676,2483,NaN,NaN,NaN,NaN,NaN,NaN
26,Audi A4,1860,3126,2652,3296,1436,2331,1691,2024,1881,...,5395,5253,2676,2483,NaN,NaN,NaN,NaN,NaN,NaN
27,Audi A5,1685,2169,2224,2587,1603,1888,1651,1599,1746,...,1997,2196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Audi A6,1374,1172,1963,1171,1506,842,1889,751,3058,...,2102,1188,1130,594,NaN,NaN,NaN,NaN,NaN,NaN
29,Audi A7,441,280,672,367,474,268,620,208,1095,...,1227,—–,643,—–,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3849,——————————–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3850,—–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3851,Chevrolet Silverado/GMC Sierra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3852,Hyundai Sonata/Kia Optima,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3853,Honda Accord/Crosstour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3854,Chevrolet Equinox/GMC Terrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3855,Dodge Grand Caravan / Chrysler Town & Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3856,Chrysler 200/Dodge Avenger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3857,Subaru Outback/Legacy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3858,Hyundai Accent/Kia Rio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3859,Chevrolet Tahoe/GMC Yukon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3860,Hyundai Tucson/Kia Sportage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3861,Chevrolet Suburban / GMC Yukon XL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3862,Nissan Frontier/Suzuki Equator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3863,Chevrolet Colorado/GMC Canyon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3864,Audi A4/A5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3865,Audi A6/A7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3866,Mercedes-Benz S-Class/CL-Class,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3867,Scion FR-S/Subaru BRZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3868,Porsche Boxster/Cayman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3869,Nissan LEAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1154,154,676,87,NaN,NaN,NaN,NaN,NaN,NaN
3870,Lexus ES350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5407,4813,2410,2215,NaN,NaN,NaN,NaN,NaN,NaN
3871,Infiniti EX35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,632,989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3872,Chevrolet Caprive PPV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3873,Porsche Boxsster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3874,* Prius Liftback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24969,24174,8500,10635,NaN,NaN,NaN,NaN,NaN,NaN
3875,* Prius V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7138,—–,3055,—–,NaN,NaN,NaN,NaN,NaN,NaN
3876,* Prius Plug-In,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21,—–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3877,* Prius C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,—–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3878,Toyota Prius/Prius V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11555,10635,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
from urls.auto_sales_urls import list_of_urls

In [61]:
list_of_urls[0:3]

["http://www.goodcarbadcar.net/2019/05/april-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2019/04/march-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',",
 "http://www.goodcarbadcar.net/2019/03/february-2019-the-best-selling-vehicles-in-america-every-vehicle-ranked/',"]